filebeat.inputs:
- type: docker
  containers:
    ids: "*"
    path: /var/lib/docker/containers
    stream: all
  json.message_key: log
  json.keys_under_root: false
  document_type: 'docker-logs'
  processors:
  - add_docker_metadata: ~

- type: syslog
  document_type: 'syslog'
  protocol.tcp:
    host: "0.0.0.0:9000"

output.elasticsearch:
  hosts: ["${ES_HOST}:${ES_PORT}"]
  username: ${ES_USER}
  password: ${ES_PWD}
  protocol: https
  ssl:
    enabled: true
    certificate_authorities: ["${CA_PATH}"]
    verification_mode: none
